# Generated by Django 4.2.6 on 2024-11-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HeartDiseasePrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("male", models.IntegerField()),
                ("age", models.IntegerField()),
                ("education", models.IntegerField()),
                ("currentSmoker", models.IntegerField()),
                ("cigsPerDay", models.IntegerField()),
                ("BPMeds", models.IntegerField()),
                ("prevalentStroke", models.IntegerField()),
                ("prevalentHyp", models.IntegerField()),
                ("diabetes", models.IntegerField()),
                ("totChol", models.IntegerField()),
                ("sysBP", models.IntegerField()),
                ("diaBP", models.IntegerField()),
                ("BMI", models.IntegerField()),
                ("heartRate", models.IntegerField()),
                ("glucose", models.IntegerField()),
                ("prediction_probability", models.IntegerField()),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
